{% set name = "dakotathon" %}
{% set version = "0.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/dakota
  git_rev: v{{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - numpy
    - nose
    - pyyaml
    - basic-modeling-interface
  run:
    - python
    - numpy
    - nose
    - pyyaml
    - basic-modeling-interface

test:
  imports:
    - dakotathon
  commands:
    - dakota_run_plugin --help
    - dakota_run_component --help

about:
  home: http://csdms-dakota.readthedocs.io
  license: MIT
  license_file: LICENSE
  summary: A Python API and BMI for the Dakota iterative systems analysis toolkit.
  dev_url: https://github.com/csdms/dakota
