{% set name = "dakotathon" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/csdms/dakota

requirements:
  build:
    - python
    - numpy
    - nose
    - pyyaml
    - basic-modeling-interface
  run:
    - python
    - numpy
    - nose
    - pyyaml
    - basic-modeling-interface

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

test:
  imports:
    - dakotathon
  commands:
    - dakota_run_plugin --help
    - dakota_run_component --help

about:
  home: http://csdms-dakota.readthedocs.io
  license: MIT
  license_file: LICENSE
  summary: A Python API and BMI for the Dakota iterative systems analysis toolkit.
  dev_url: https://github.com/csdms/dakota
