{% set name = "dakotathon" %}
{% set version = "0.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/{{ name }}
  git_rev: v{{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - numpy
    - pyyaml
  run:
    - python
    - numpy
    - pyyaml
    - bmipy

test:
  requires:
    - nose
  imports:
    - dakotathon
  commands:
    - dakota_run_plugin --help
    - dakota_run_component --help

about:
  home: http://csdms.colorado.edu/wiki/Model:Dakotathon
  license: MIT
  license_file: LICENSE
  summary: A Python API and BMI for the Dakota iterative systems analysis toolkit.
  doc_url: http://csdms-dakota.readthedocs.io
  dev_url: https://github.com/csdms/dakotathon
