language: generic

os:
  - linux
  - osx

env:
  matrix:
    - PYTHON="3.7"
  global:
    - MINICONDA_URL_BASE=" https://repo.anaconda.com/miniconda/Miniconda3-latest"
    - secure: "q4TF3wVmFfXL6o/n57AJZ2pxCyueDiSgWOGnNtHPxheAEJ2Fv1x+0Yw39abfeT92kJe9KzFIN6NioCKejkHEexmbtSEQqin+pHmbjc81FYnbC6L/MEIquv4Oa/KKMv1kdS4J1h+i1VHEQ7U82z7G4Ld1usyvEZSVjajiYSvo/XGI0udV4ZBt+OJTXV+7hJQpVbF8NOR5E4AYWq1Qnvl91RwCpi8VypNjwwbinfR1Zf4eAMN6XnpYoQfSpH71/nOaNa1jz+6/xl9TqE/Zg0qGF3+em1hSSIASkjcjkp2kVRypoHInYEndTAxU/scSxDu9TMWY16K7GLYEfirvukyPzqqgIQMcH+YK3dimaUEncfEKl/mBWWP3Ctqs7gHFcOVjgkSMAXw7V/Ns1ZY+Q97lXtjysrIHq4G2QweOOPLkJb/vhqnH9SfDi04jkDKT2nF1yMJrqKGbgC/KsYdZvO1XwvR61v1e5gAl8+PxxllhGPP4kC7lfvVFox2Nz0OIRlnSxYrnquFSxg5BZd5VrwQ9U+wruX72fFpbELSZcjiYqsnKA4pJVAIZH4RB6k1cC3t2a1fHgKJhWrP1e2CxIGRbMXZFLdW2GieF3c7mgo8up1+t1pvU2NL9t0BeseR/7wIsysHXt2rfJWyx/oIAUkFtT1ZrloK93uO9mx3cXk0JI1I="

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew remove --force $(brew list)
      brew cleanup -s
      rm -rf $(brew --cache)
      OS="MacOSX-x86_64"
    else
      OS="Linux-x86_64"
    fi

install:
  - curl $MINICONDA_URL_BASE-$OS.sh > $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set channel_priority strict
  - conda config --add channels csdms-stack
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda create -n test python=$PYTHON conda-build anaconda-client
  - source activate test
  - conda info -a 

script:
  - conda build ./recipe

after_success:
  - curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py > $HOME/anaconda_upload.py
  - echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --token=-
