language: generic

os:
  - linux
  - osx

env:
  matrix:
    - PYTHON="3.6"
    - PYTHON="3.7"
    - PYTHON="3.8"
  global:
    - MINICONDA_URL_BASE=" https://repo.anaconda.com/miniconda/Miniconda3-latest"
    - secure: "dMvcvkDOhjt5pUxbSRxxfp47L/7AQC7b0jLCM5n9p+3EMoT97HAo7RswyuWWtjoxNGDcJnWF1kX7Cm91HU+B5LEujDt07k+ahIC6sWFlZ/hiX/gjTAx2VimkYc6ue/JoQeJSp9C8P/ujNbU2bxANR4ZqAEThyjmWgwDdIYKuMkibnoRD6tgS9btBCdtiHz/nAjSAWkudmL/cL+X14WIu2OC4AXqi6lPuWV66elFU8NPDK/XsPmD4hwO5U1sN/icYgCbxPoBBa3hvUYxMAk2U1dmKIWpr0NJogchIWR6Ty84xlL2ekKSB67759mcaWwQOc/q4iOhR1AD+GSYmdOT+UOW9adElpSjibq1sJy8wbgcgcIt9vLXv/DgcFhi1jSu1GpwijiDUJfHqcyiVJ9oBA0cO4qJokNX6yo2cYz0NEDpG3xE1mQ/nVRroTY5t9um5R5EjhdYH9BuNlG4ZOWBVymPE0RyoXhqB9K2fr8j1oM928rqXg5B/O41AFJNmPWA7loE83xWYJGBQJ4vpDPg8xuZGRlc8kRBiqV3hiO8wj5Jzr1CaPjZ6e68Tf9s0g7nwrFjrqALL4cEDaccDU4UZ9TMWBatRRZ6h1YygkBbWnF3lNDuXqRDRYkikmlVhLq4+U/YAJaep0YcdI8rSTYkyPDrPAjUVVKxQJoZryIq5f4k="

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew remove --force $(brew list)
      brew cleanup -s
      rm -rf $(brew --cache)
      OS="MacOSX-x86_64"
    else
      OS="Linux-x86_64"
    fi

install:
  - curl $MINICONDA_URL_BASE-$OS.sh > $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set channel_priority strict
  - conda config --add channels csdms-stack
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda create -n test python=$PYTHON conda-build anaconda-client
  - source activate test
  - conda info -a 

script:
  - conda build ./recipe

after_success:
  - curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py > $HOME/anaconda_upload.py
  - echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --token=-
